# Stage: Development
FROM node:22-alpine

WORKDIR /app

# Installation des dépendances
COPY package*.json ./
RUN npm install

# Copie du reste des fichiers (sera surchargé par le volume en dev, mais utile pour le build initial)
COPY . .

# Exposition du port Angular par défaut
EXPOSE 4200

# Démarrage en mode Watch avec Polling (pour Windows/Docker) et Host 0.0.0.0
# --configuration docker : Utilise l'environnement Docker (apiUrl: http://backend:3000/api)
# --poll 2000 : Vérifie les changements de fichiers toutes les 2s (fixe les problèmes de volumes Docker Windows)
# --host 0.0.0.0 : Rend le serveur accessible depuis l'extérieur du conteneur
# --disable-host-check : Évite les erreurs de sécurité liées au nom d'hôte Docker
CMD ["npx", "ng", "serve", "--configuration", "docker", "--host", "0.0.0.0", "--poll", "2000", "--disable-host-check"]
